[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "rafael-lopes-portfolio"

[services.source]
repo = "RafaelLopesPinheiro/My-landpage-main"

[services.variables]
ENVIRONMENT = "production"